// Auto-generated by dev/generate-sdk.sh — do not edit manually.
// Source: src/**/*Result.php  |  Regenerate: ./dev/generate-sdk.sh

export interface LiveUpdateResult {
  messageId: string;
}

export interface ProcessPaymentResult {
  paymentId: string;
  amountCents: number;
  currency: string;
  processedAt: string; // DateTimeImmutable → ISO 8601
}
