// Auto-generated by dev/generate-sdk.sh — do not edit manually.
// Source: src/**/*Result.php  |  Regenerate: ./dev/generate-sdk.sh

export interface CompleteTaskResult {
  id: string;
  title: string;
  completed: boolean;
  completedAt: string;
}

export interface CreateTaskResult {
  id: string;
  title: string;
  completed: boolean;
  createdAt: string;
}

export interface ListTasksResult {
  items: unknown[];
}

export interface LiveUpdateResult {
  messageId: string;
}

export interface VerifyAttestationResult {
  subjectName: string;
  subjectDigest: string;
  builderId: string;
  sourceCommit: string | null;
}
