#!/usr/bin/env bash
# Generates TypeScript type definitions from src/**/*Result.php classes.
# Output: packages/client-sdk/types.ts (or the path given as $2).
#
# Usage: ./dev/generate-sdk.sh [src-dir] [out-file]
#   src-dir  default: src
#   out-file default: packages/client-sdk/types.ts

set -euo pipefail

SRC_DIR="${1:-src}"
OUT_FILE="${2:-packages/client-sdk/types.ts}"

mkdir -p "$(dirname "$OUT_FILE")"

php -- - "$SRC_DIR" "$OUT_FILE" <<'PHPEOF'
<?php
declare(strict_types=1);

// argv: [0]=script-name [1]="-" [2]=srcDir [3]=outFile
$srcDir  = $argv[2] ?? 'src';
$outFile = $argv[3] ?? 'packages/client-sdk/types.ts';

$typeMap = [
    'string'             => 'string',
    'int'                => 'number',
    'float'              => 'number',
    'bool'               => 'boolean',
    'array'              => 'unknown[]',
    'DateTimeImmutable'  => 'string',
    '\DateTimeImmutable' => 'string',
];

function phpTypeToTs(string $type, array $map): string
{
    $nullable = str_starts_with($type, '?');
    $base     = $nullable ? substr($type, 1) : $type;
    $ts       = $map[$base] ?? 'unknown';

    return $nullable ? "{$ts} | null" : $ts;
}

function camelCase(string $snake): string
{
    return lcfirst(str_replace('_', '', ucwords($snake, '_')));
}

$files = new RegexIterator(
    new RecursiveIteratorIterator(new RecursiveDirectoryIterator($srcDir)),
    '/\/Application\/[A-Z][a-zA-Z]+Result\.php$/',
);

$interfaces = [];

foreach ($files as $file) {
    $source    = file_get_contents((string) $file);
    $className = basename((string) $file, '.php');

    // Match: public type $name
    preg_match_all(
        '/public\s+(?:readonly\s+)?(\??\S+)\s+\$(\w+)/m',
        $source,
        $matches,
        PREG_SET_ORDER,
    );

    if (empty($matches)) {
        continue;
    }

    $props = [];
    foreach ($matches as $m) {
        [, $phpType, $propName] = $m;
        $tsType  = phpTypeToTs($phpType, $typeMap);
        $comment = str_contains($phpType, 'DateTime') ? ' // DateTimeImmutable → ISO 8601' : '';
        $props[] = "  {$propName}: {$tsType};{$comment}";
    }

    $interfaces[$className] = "export interface {$className} {\n" . implode("\n", $props) . "\n}";
}

ksort($interfaces);

$banner  = "// Auto-generated by dev/generate-sdk.sh — do not edit manually.\n";
$banner .= '// Source: src/**/*Result.php  |  Regenerate: ./dev/generate-sdk.sh' . "\n\n";
$content = $banner . implode("\n\n", $interfaces) . "\n";

file_put_contents($outFile, $content);

$count = count($interfaces);
echo "Generated {$count} interface(s) → {$outFile}\n";
PHPEOF
